stages:
  - doc

doc_job_1:
  stage: doc
  tags:
    - fjci
  script:
    - cmd /c .\docfx_project\BuildDoc.bat
    - cmd /c .\docfx_project\AutoUpdate.bat

doc_job_2:
  when:
    on_failure
  stage: doc
  tags:
    - ci
  script:
    - cmd /c .\docfx_project\BuildDoc.bat
    - cmd /c .\docfx_project\AutoUpdate.bat
